# Generated by PySCeS 1.0.1 (2022-03-14 20:28)
 
# Keywords
Description: EnzymeML_Lagerman
Modelname: EnzymeML_Lagerman
Output_In_Conc: True
Species_In_Conc: True
 
# GlobalUnitDefinitions
UnitSubstance: mole, 1.0, 0, 1
UnitVolume: litre, 1.0, 0, 1
UnitTime: second, 1.0, 0, 1
UnitLength: metre, 1.0, 0, 1
UnitArea: metre, 1.0, 0, 2
 
# Compartments
Compartment: v0, 5.0, 3 
 
# Reactions
r0@v0:
    c1 = p0 + s1
    v_r*(K_n*c1-p0*s1)

r1@v0:
    c0 = p0 + s0
    v_r*(r1_K_s*c0-p0*s0)

r2@v0:
    c0 > p1
    r2_k_2*c0

r3@v0:
    c3 = c0 + s0
    v_r*(K_si*c3-c0*s0)

r4@v0:
    c5 = p1 + s0
    v_r*(K_si*c5-p1*s0)

r5@v0:
    c5 > p0 + s3
    r5_k_6*c5

r6@v0:
    p1 > p0 + s3
    r6_k_3*p1

r7@v0:
    c2 = p0 + s3
    v_r*(r7_K_pg*c2-p0*s3)

r8@v0:
    c4 = p1 + s1
    v_r*(K_n*c4-p1*s1)

r9@v0:
    c4 > p0 + s3 + s1
    r9_k_5*c4

r10@v0:
    c4 = c6
    r10_k_4*c4-r10_k_4b*c6

r11@v0:
    c6 = p0 + s2
    v_r*(r11_K_p*c6-p0*s2)

r12@v0:
    p0 > p2
    r12_k_d*p0
 
# Fixed species
 
# Variable species
p0@v0 = 0.0002
p1@v0 = 0.0
p2@v0 = 0.0
c0@v0 = 0.0
c1@v0 = 0.0
c2@v0 = 0.0
c3@v0 = 0.0
c4@v0 = 0.0
c5@v0 = 0.0
c6@v0 = 0.0
s0@v0 = 20.0
s1@v0 = 42.0
s2@v0 = 0.0
s3@v0 = 0.0
 
# Parameters
v_r = 1000000000.0
K_n = 11.00542741
r1_K_s = 5.676255758
r2_k_2 = 652085.5139
K_si = 6.346729249
r5_k_6 = 393169.3931
r6_k_3 = 8.93817854
r7_K_pg = 47.34446037
r9_k_5 = 672295.823
r10_k_4 = 1870570.524
r10_k_4b = 42451.1374
r11_K_p = 0.9433184993
r12_k_d = 0.5149464784
 

